[book]
authors = ["Starknet Community with support from Starkware and the Starknet Foundation"]
language = "en"
multilingual = false
src = "src"
title = "The Starknet Book"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/starknet-edu/starknetbook"
